### PR TITLE
984 limits error messages

### LINKED ISSUE #984: Improve message description for limit errors (a.k.a 429 Too many Request)
When the database times out, we respond with:

```
{
  error: [
    "You are over platform's limits. Please contact us to know more details"
  ],
  type: "limit"
}
```

We need to improve the message to make the user understand that either the database timed out or the user reached his rate-limit.

### PR DESCRIPTION
**Pull request by enekid**
closes #984

When a DB timeout error arises caused by our `limits system`, the user should be aware of the actual error reason. Currently, the API responses with a cryptic 429 http error:

```json
{
    "error": [
        "You are over platform's limits. Please contact us to know more details."
    ],
    "context": "limit",
    "detail": "datasource"
}
```

This PR rephrases the error message, taking care not to break `carto.js` error handling.

```json
{
    "error": [
        "You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details."
    ],
    "type": "limit",
    "subtype": "datasource"
}
```

### CODE REVIEW

File: lib/cartodb/api/middlewares/error-middleware.js [hunk 1]
```diff
@@ -56,16 +56,20 @@ function populateTimeoutErrors (errors) {
             error.subtype = 'render';
         }
 
-        if (isDatasourceTimeoutError(error)) {
-            error.subtype = 'datasource';
-        }
+        const IS_DATASOURCE_TIMEOUT_ERROR = isDatasourceTimeoutError(error);
 
         if (isTimeoutError(error)) {
             error.message = 'You are over platform\'s limits. Please contact us to know more details';
```
Comment (oleurud) [inline lib/cartodb/api/middlewares/error-middleware.js]: Should we add info about the `render timeout`?

Comment (oleurud) [reply lib/cartodb/api/middlewares/error-middleware.js]: And the same question with rate limit error

Comment (oleurud) [reply lib/cartodb/api/middlewares/error-middleware.js]: I mean, I would take advantage of it to change the rest of messages in the same situation

Comment (enekid) [reply lib/cartodb/api/middlewares/error-middleware.js]: We should tackle this in another issue or when/if we do an `API errors` refactor

Comment (oleurud) [reply lib/cartodb/api/middlewares/error-middleware.js]: My suggestion for rate limts:
`You are over platform\'s limits: too many requests. Please contact us to know more details`

And my suggestion for rate limts render timeout is to use the same message as db timeout

Comment (enekid) [reply lib/cartodb/api/middlewares/error-middleware.js]: The updated limit error messages are as follows:
* **rate** - `You are over platform's limits: too many requests. Please contact us to know more details`
* **db** - `You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details.`
* **render** - `You are over platform's limits: Render timeout error. Contact CARTO support for more details.`

**Comment by enekid** [comment]
The updated limit error messages are as follows:
* **rate** - `You are over platform's limits: too many requests. Please contact us to know more details`
* **db** - `You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details.`
* **render** - `You are over platform's limits: Render timeout error. Contact CARTO support for more details.`
