### PR TITLE
725 fix polygon count

### LINKED ISSUE #725: Widget figure from polygon count problems
Polygon count figures are not showing the right answers. It is returning more polygons than the ones that can be shown on screen.

We are using PostGis operator  '&&' (uses bounding boxes) instead of using the 'ST_Intersects' function

### PR DESCRIPTION
**Pull request by oleurud**
Fixes #725

### CODE REVIEW

File: test/acceptance/dataviews/polygonCount.js [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+
+    afterEach(function(done) {
+        if (this.testClient) {
+            this.testClient.drain(done);
+        } else {
+            done();
+        }
+    });
+
+    var polygon1 = {
```
Comment (rochoa) [inline test/acceptance/dataviews/polygonCount.js]: What about giving names closer to the problem. Something like `notIntersectingLeftTriangle`, `intersectingTriangle`, `notIntersectingRightTriangle`?

File: test/acceptance/dataviews/polygonCount.js [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+                }
+            }
+        },
+        [
+            {
+                "id": "a0",
+                "type": "source",
+                "params": {
+                    "query": `  
+                                SELECT
```
Comment (rochoa) [inline test/acceptance/dataviews/polygonCount.js]: In the same line, what about giving a _category_ name to each of the polygons and using an aggregation dataview to check the only returned polygon is the expected one.

File: test/acceptance/widgets/regressions.js [hunk 3]
```diff
@@ -218,6 +218,113 @@ describe('widgets-regressions', function() {
...
+                ]
+            };
+
+            this.testClient = new TestClient(mapConfig, 1234);
+            var params = {
+                bbox: '-77.34374999999999,45.82879925192134,17.578125,55.97379820507658'
+            };
+            this.testClient.getDataview('val_formula', params, function(err, dataview) {
+                assert.equal(dataview.categories.length, 1);
+                assert.equal(dataview.categories[0].category, 'intersectingTriangle');
```
Comment (rochoa) [inline test/acceptance/widgets/regressions.js]: ❤️

**Comment by rochoa** [comment]
So nice, thanks for improving the tests. 👍 

:shipit:

File: test/acceptance/widgets/regressions.js [hunk 4]
```diff
@@ -218,6 +218,113 @@ describe('widgets-regressions', function() {
...
+        it('should not count the polygons outside the bounding box', function(done) {
+
+            // $               %        $ = not intersecting left triangle
+            // $$  **VVVVV**  %%        % = not intersecting right triangle
+            // $$$  *VVVVV*  %%%        * = intersecting triangle
+            // $$$$  *****  %%%%        V = bounding box
+            // $$$$$  ***  %%%%%
+            // $$$$$$  *  %%%%%%
+            // $$$$$$$   %%%%%%%
+            // $$$$$$$$ %%%%%%%%
```
Comment (dgaubert) [inline test/acceptance/widgets/regressions.js]: Great! ❤️

File: test/acceptance/widgets/regressions.js [hunk 5]
```diff
@@ -218,6 +218,113 @@ describe('widgets-regressions', function() {
...
+                    }
+                ]
+            };
+
+            this.testClient = new TestClient(mapConfig, 1234);
+            var params = {
+                bbox: '-77.34374999999999,45.82879925192134,17.578125,55.97379820507658'
+            };
+            this.testClient.getDataview('val_formula', params, function(err, dataview) {
+                assert.equal(dataview.categories.length, 1);
```
Comment (dgaubert) [inline test/acceptance/widgets/regressions.js]: Do you mind to assert if there was an error? It will be helpful to know what's happening if something went wrong.

We usually use `assert.ifError(err)`. Thus mocha prints the stack trace.

File: test/acceptance/widgets/regressions.js [hunk 6]
```diff
@@ -218,6 +218,113 @@ describe('widgets-regressions', function() {
...
+                type: "Polygon",
+                coordinates:[[
+                    [-117.42187500000001,68.13885164925573],
+                    [-35.859375,20.96143961409684],
+                    [59.4140625,68.52823492039876],
+                    [-117.42187500000001,68.13885164925573]
+                ]]
+            };
+
+            let query = `
```
Comment (dgaubert) [inline test/acceptance/widgets/regressions.js]: If the variable won’t be reassigned I'd use `const` instead of `let`. Seems to be a new convention in ES6. :man_shrugging:

File: test/acceptance/widgets/regressions.js [hunk 7]
```diff
@@ -218,6 +218,113 @@ describe('widgets-regressions', function() {
...
+                        '${JSON.stringify(notIntersectingRightTriangle)}'
+                    ), 4326), 3857), 2, 'notIntersectingRightTriangle'
+                UNION
+                SELECT
+                    ST_TRANSFORM(ST_SETSRID(ST_GeomFromGeoJSON(
+                        '${JSON.stringify(intersectingTriangle)}'
+                    ), 4326), 3857), 3, 'intersectingTriangle'
+            `;
+
+            var mapConfig = {
```
Comment (dgaubert) [inline test/acceptance/widgets/regressions.js]: Same here, to keep consistency I encourage you to use `const`.

File: test/acceptance/widgets/regressions.js [hunk 8]
```diff
@@ -218,6 +218,113 @@ describe('widgets-regressions', function() {
...
+                        "type": "source",
+                        "params": {
+                            "query": query
+                        }
+                    }
+                ]
+            };
+
+            this.testClient = new TestClient(mapConfig, 1234);
+            var params = {
```
Comment (dgaubert) [inline test/acceptance/widgets/regressions.js]: please use `const`.
